# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180114_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
