# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180114_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(auto_now_add=True)),
                ('updatedate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(auto_now_add=True)),
                ('updatedate', models.DateField(auto_now=True)),
                ('journaltxt', models.TextField(max_length=2000)),
                ('journalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Journal')),
            ],
        ),
    ]
