# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_journal_journalentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentries',
            old_name='journalid',
            new_name='journal_id',
        ),
        migrations.AddField(
            model_name='journal',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Person'),
        ),
    ]
