# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180114_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Person'),
        ),
    ]
