# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20180114_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
