# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_campain'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
