# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='telephone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
